[package]
name = "hash-gen"
version = "0.1.0"
authors = ["jfarabee <jfarabee@asu.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.5.6"
blake2 = "0.9"
md-5 = "0.9.1"
sha3 = "0.9.1"
